import { getDb } from "../api/queries/connection";
import { sources, articles, categories } from "./schema";

const db = getDb();

async function seed() {
  console.log("Seeding BrightSide database...");

  // Seed sources
  const sourceData = [
    { name: "Solutions Journalism Network", url: "https://solutionsjournalism.org", category: "investigative" as const, trustScore: "0.95", regionFocus: "Global" },
    { name: "Positive.News", url: "https://positive.news", category: "human_curated" as const, trustScore: "0.82", regionFocus: "Global" },
    { name: "BRAC Reports", url: "https://brac.net", category: "institutional" as const, trustScore: "0.90", regionFocus: "Bangladesh" },
    { name: "Nature", url: "https://nature.com", category: "academic" as const, trustScore: "0.98", regionFocus: "Global" },
    { name: "Good News Network", url: "https://goodnewsnetwork.org", category: "human_curated" as const, trustScore: "0.75", regionFocus: "USA" },
    { name: "The Daily Star", url: "https://thedailystar.net", category: "institutional" as const, trustScore: "0.78", regionFocus: "Bangladesh" },
    { name: "The Lancet", url: "https://thelancet.com", category: "academic" as const, trustScore: "0.98", regionFocus: "Global" },
    { name: "World Bank", url: "https://worldbank.org", category: "institutional" as const, trustScore: "0.96", regionFocus: "Global" },
    { name: "IDCOL", url: "https://idcol.org", category: "institutional" as const, trustScore: "0.88", regionFocus: "Bangladesh" },
  ];

  await db.insert(sources).values(sourceData);
  console.log(`  Inserted ${sourceData.length} sources`);

  // Seed categories
  const categoryData = [
    { name: "Health", emoji: "⚕️", description: "Medical breakthroughs, public health improvements, disease eradication" },
    { name: "Environment", emoji: "🌿", description: "Conservation, reforestation, renewable energy, climate solutions" },
    { name: "Innovation", emoji: "💡", description: "Technology, science, clean energy, infrastructure" },
    { name: "Community", emoji: "🤝", description: "Grassroots movements, social cohesion, volunteerism" },
    { name: "Economic", emoji: "📈", description: "Poverty reduction, entrepreneurship, fair trade" },
    { name: "Peace", emoji: "🕊️", description: "Conflict resolution, diplomacy, reconciliation" },
  ];

  await db.insert(categories).values(categoryData);
  console.log(`  Inserted ${categoryData.length} categories`);

  // Seed articles
  const articleData = [
    {
      title: "Rwanda's Community Health Workers Eliminated Maternal Deaths in One District",
      summary: "A network of 45,000 trained volunteers achieved zero maternal deaths through motorcycle transport and community education.",
      content: "In the remote district of Kirehe, Rwanda, a remarkable transformation has occurred over the past five years. A network of 45,000 community health workers, equipped with medical kits and motorcycle ambulances, has achieved what many thought impossible: zero maternal deaths in 2024.",
      url: "#",
      imageUrl: "/assets/featured-rwanda.jpg",
      publishedAt: new Date("2026-06-10T08:00:00Z"),
      sourceId: 1,
      region: "Rwanda",
      regionTier: "underreported" as const,
      category: "Health",
      hopeScore: "0.950",
      verifiedFacts: "0.980",
      systemicImpact: "0.960",
      actionability: "0.880",
      novelty: "0.820",
      representation: "0.900",
      tier: "gold" as const,
      isVerified: true,
      hasAction: true,
      actionsJson: JSON.stringify([
        { type: "donate", label: "Support CHW Programs", url: "#" },
        { type: "volunteer", label: "Find Medical Volunteer Ops", url: "#" },
        { type: "learn", label: "Learn About CHW Model", url: "#" },
      ]),
    },
    {
      title: "How Medellín Transformed From Murder Capital to Innovation Hub",
      summary: "Colombia's second-largest city achieved an 80% reduction in homicides through cable cars, library-parks, and community investment.",
      content: "Three decades ago, Medellín was the most dangerous city in the world. Today, it is a UNESCO City of Learning and a global model for urban transformation.",
      url: "#",
      imageUrl: "/assets/card-community.jpg",
      publishedAt: new Date("2026-06-09T14:30:00Z"),
      sourceId: 2,
      region: "Colombia",
      regionTier: "developing" as const,
      category: "Innovation",
      hopeScore: "0.820",
      verifiedFacts: "0.880",
      systemicImpact: "0.940",
      actionability: "0.720",
      novelty: "0.760",
      representation: "0.700",
      tier: "verified" as const,
      isVerified: true,
      hasAction: false,
    },
    {
      title: "Bangladesh Village Builds Floating Gardens to Beat Floods",
      summary: "Farmers in flood-prone regions are producing 3 tons of vegetables monthly using water hyacinth and bamboo rafts.",
      content: "In the flood-prone wetlands of southern Bangladesh, a centuries-old agricultural technique is being revived with modern twists. Floating gardens -- rafts woven from water hyacinth and bamboo -- are allowing farmers to grow crops even when their land is submerged for months.",
      url: "#",
      imageUrl: "/assets/bangladesh-climate.jpg",
      publishedAt: new Date("2026-06-09T10:00:00Z"),
      sourceId: 3,
      region: "Bangladesh",
      regionTier: "underreported" as const,
      category: "Environment",
      hopeScore: "0.760",
      verifiedFacts: "0.800",
      systemicImpact: "0.780",
      actionability: "0.680",
      novelty: "0.740",
      representation: "0.900",
      tier: "verified" as const,
      isVerified: true,
      hasAction: false,
    },
    {
      title: "Scientists Develop Plastic-Eating Enzyme That Works in Hours",
      summary: "MIT researchers have engineered an enzyme that breaks down PET plastic 6 times faster than previous versions.",
      content: "Researchers at MIT have developed a new variant of the PETase enzyme that can break down polyethylene terephthalate (PET) plastic six times faster than previous versions.",
      url: "#",
      imageUrl: "/assets/card-innovation.jpg",
      publishedAt: new Date("2026-06-08T16:00:00Z"),
      sourceId: 4,
      region: "Global",
      regionTier: "global" as const,
      category: "Innovation",
      hopeScore: "0.740",
      verifiedFacts: "0.960",
      systemicImpact: "0.720",
      actionability: "0.580",
      novelty: "0.900",
      representation: "0.500",
      tier: "verified" as const,
      isVerified: true,
      hasAction: false,
    },
    {
      title: "Strangers Raise $50,000 for Homeless Man Who Returned Wallet",
      summary: "A community fundraiser secured an apartment and fresh start for a man who chose honesty over desperation.",
      content: "When James Robertson found a wallet containing $2,300 in cash on a Chicago street corner, he didn't hesitate. Despite being homeless for three years, he walked three miles to return it to its owner.",
      url: "#",
      imageUrl: "/assets/card-economic.jpg",
      publishedAt: new Date("2026-06-08T12:00:00Z"),
      sourceId: 5,
      region: "USA",
      regionTier: "western" as const,
      category: "Community",
      hopeScore: "0.580",
      verifiedFacts: "0.720",
      systemicImpact: "0.380",
      actionability: "0.800",
      novelty: "0.620",
      representation: "0.400",
      tier: "constructive" as const,
      isVerified: false,
      hasAction: true,
      actionsJson: JSON.stringify([
        { type: "donate", label: "Support Housing Programs", url: "#" },
        { type: "volunteer", label: "Find Local Shelters", url: "#" },
      ]),
    },
    {
      title: "Kenya Launches Africa's Largest Electric Bus Fleet",
      summary: "Nairobi's new fleet of 200 electric buses will reduce city transport emissions by 35% within two years.",
      content: "Nairobi has launched the largest electric bus fleet in Africa, with 200 zero-emission vehicles hitting the streets this month.",
      url: "#",
      imageUrl: "/assets/card-environment.jpg",
      publishedAt: new Date("2026-06-07T09:00:00Z"),
      sourceId: 6,
      region: "Kenya",
      regionTier: "developing" as const,
      category: "Environment",
      hopeScore: "0.840",
      verifiedFacts: "0.900",
      systemicImpact: "0.880",
      actionability: "0.620",
      novelty: "0.780",
      representation: "0.700",
      tier: "verified" as const,
      isVerified: true,
      hasAction: false,
    },
    {
      title: "Nepal's All-Female Ranger Unit Protects Endangered Rhinos",
      summary: "The first all-female anti-poaching unit in Chitwan National Park has achieved zero rhino poaching for 18 consecutive months.",
      content: "In Chitwan National Park, a team of 42 female rangers is rewriting the rules of wildlife conservation. Since their deployment 18 months ago, rhino poaching in their sector has dropped to zero.",
      url: "#",
      imageUrl: "/assets/card-peace.jpg",
      publishedAt: new Date("2026-06-07T07:00:00Z"),
      sourceId: 2,
      region: "Nepal",
      regionTier: "underreported" as const,
      category: "Environment",
      hopeScore: "0.880",
      verifiedFacts: "0.860",
      systemicImpact: "0.840",
      actionability: "0.580",
      novelty: "0.820",
      representation: "0.900",
      tier: "gold" as const,
      isVerified: true,
      hasAction: false,
    },
    {
      title: "Brazilian Favela Youth Code Their Way Out of Poverty",
      summary: "A coding bootcamp in Rio's favelas has placed 3,000 graduates in tech jobs with an average salary of $45,000.",
      content: "In the narrow alleys of Complexo do Alemão, one of Rio de Janeiro's largest favelas, a quiet revolution is taking place.",
      url: "#",
      imageUrl: "/assets/card-community.jpg",
      publishedAt: new Date("2026-06-06T11:00:00Z"),
      sourceId: 1,
      region: "Brazil",
      regionTier: "developing" as const,
      category: "Economic",
      hopeScore: "0.790",
      verifiedFacts: "0.880",
      systemicImpact: "0.820",
      actionability: "0.740",
      novelty: "0.760",
      representation: "0.700",
      tier: "verified" as const,
      isVerified: true,
      hasAction: true,
      actionsJson: JSON.stringify([
        { type: "donate", label: "Support Coding Bootcamps", url: "#" },
        { type: "learn", label: "Explore Tech Education", url: "#" },
      ]),
    },
    {
      title: "New Malaria Vaccine Shows 94% Efficacy in Phase 3 Trials",
      summary: "A new RNA-based malaria vaccine developed by a Nigerian-German research partnership shows unprecedented protection.",
      content: "A groundbreaking malaria vaccine has shown 94% efficacy in Phase 3 clinical trials, potentially saving hundreds of thousands of lives annually.",
      url: "#",
      imageUrl: "/assets/card-health.jpg",
      publishedAt: new Date("2026-06-06T08:00:00Z"),
      sourceId: 7,
      region: "Nigeria",
      regionTier: "underreported" as const,
      category: "Health",
      hopeScore: "0.930",
      verifiedFacts: "0.980",
      systemicImpact: "0.960",
      actionability: "0.520",
      novelty: "0.920",
      representation: "0.900",
      tier: "gold" as const,
      isVerified: true,
      hasAction: false,
    },
    {
      title: "Indian Villages Achieve 100% Solar Power Independence",
      summary: "A cluster of 12 villages in Rajasthan now runs entirely on solar energy, eliminating grid dependency entirely.",
      content: "In the sun-baked landscape of rural Rajasthan, a clean energy revolution is unfolding. Twelve villages, once plagued by daily power outages, have achieved complete energy independence.",
      url: "#",
      imageUrl: "/assets/card-innovation.jpg",
      publishedAt: new Date("2026-06-05T13:00:00Z"),
      sourceId: 8,
      region: "India",
      regionTier: "developing" as const,
      category: "Innovation",
      hopeScore: "0.870",
      verifiedFacts: "0.940",
      systemicImpact: "0.860",
      actionability: "0.620",
      novelty: "0.780",
      representation: "0.700",
      tier: "gold" as const,
      isVerified: true,
      hasAction: false,
    },
    {
      title: "Bangladesh's Solar Home Systems Reach 6 Million Households",
      summary: "The world's largest off-grid solar program has now powered 6 million rural homes, creating 100,000 green jobs.",
      content: "Bangladesh's Infrastructure Development Company Limited (IDCOL) has achieved a historic milestone: 6 million solar home systems now power rural households across the country.",
      url: "#",
      imageUrl: "/assets/bangladesh-education.jpg",
      publishedAt: new Date("2026-06-05T06:00:00Z"),
      sourceId: 9,
      region: "Bangladesh",
      regionTier: "underreported" as const,
      category: "Innovation",
      hopeScore: "0.910",
      verifiedFacts: "0.920",
      systemicImpact: "0.940",
      actionability: "0.720",
      novelty: "0.700",
      representation: "0.900",
      tier: "gold" as const,
      isVerified: true,
      hasAction: true,
      actionsJson: JSON.stringify([
        { type: "donate", label: "Support Solar Programs", url: "#" },
        { type: "learn", label: "Learn About SHS", url: "#" },
      ]),
    },
  ];

  await db.insert(articles).values(articleData);
  console.log(`  Inserted ${articleData.length} articles`);

  console.log("Seeding complete!");
}

seed().catch(console.error);
